### ISSUE TITLE
TimeDelta constructor should accept arguments of type float

### ISSUE THREAD

**Issue by sbethur** [ni/hightime#32]
It is fairly typical for Python bindings to wrap the time values returned by a driver runtime, in TimeDelta objects before returning it to user. If driver runtime returned value as float, there is no easy way to create a TimeDelta object from it.

```
>>> t = hightime.TimeDelta(seconds=0.025)
>>> print(t)
0:00:00
>>> t = datetime.timedelta(seconds=0.025)
>>> print(t)
0:00:00.025000
```

**Comment by thejcannon** [comment]
According to the `datetime.timedelta` [documentation](https://docs.python.org/3/library/datetime.html#datetime.timedelta)

> All arguments are optional and default to 0. Arguments may be integers or floats, and may be positive or negative.

**Comment by sbethur** [comment]
`highttime.TimeDelta` restricts `frac_seconds_exponent` to be negative. Maybe it should not?

**Comment by thejcannon** [comment]
Well, that part of the API is weird. What I wanted to highlight though is that it denotes the arguments may be integers or floats. 👍
