### ISSUE TITLE
Subtracting a hightime from another hightme returns inaccurate seconds result

### ISSUE THREAD

**Issue by DeborahOoi96** [ni/hightime#38]
Observed in https://github.com/ni/nidaqmx-python/pull/504#discussion_r1497055100

This is the formula we are using to get the time in seconds from Jan 1 1970 to dt:
`seconds_since_1970 = int((dt - _EPOCH_1970) / ht_timedelta(seconds=1))`

If we were to run this with dt = Jan 1, 1850 + 1us, we will get -3786825599
But if we were to run it with dt = Jan 1, 1850 + 1femtosecond, we will get -3786825600

Is this an expected behaviour? Is the number is too small to be reflected in the seconds? Or are the changes somehow not propogated up correctly to seconds?

**Comment by vvacharya** [comment]
> Is this an expected behaviour? Is the number is too small to be reflected in the seconds? Or are the changes somehow not propogated up correctly to seconds?
 
Yes, this was expected behavior. When casting to int, the number of femtoS or uS will be too small to see.
However, we have added `precision_total_seconds` in 0.2.2 that uses the Python Decimal concept to caclulate to 64 significant figures.
