### ISSUE TITLE
`SITimeUnit` or `SiTimeUnit`

### ISSUE THREAD

**Issue by epage** [ni/hightime#6]
PEP8
> Note: When using acronyms in CapWords, capitalize all the letters of the acronym. Thus HTTPServerError is better than HttpServerError.

https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles

So this is probably right but (as I find out as I'm creating this).  Still leaving it here so its recorded in case we think of this again.

Note: I think we didn't see that one phrase in XNET and did not capitalize all the letters.  Or maybe I did and made a decision to ignore it?  I thought this came up but https://github.com/ni/nixnet-python/pull/176 is the only case I'm finding it which is long after the fact.

**Comment by tkrebes** [comment]
I'd leave it as SITimeUnit. SI is a French acronym that stands for "International System":
https://en.wikipedia.org/wiki/International_System_of_Units
